import type { Metadata } from "next";
import { Geist, Geist_Mono, Crimson_Pro, Lora, Varela, DM_Sans, DM_Serif_Display } from "next/font/google";
import { SanityLive } from "@/sanity/live";
import "./globals.css";

// FONTS 

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"]
});

const DMSerifDisplay = DM_Serif_Display({
  weight: "400",
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"]
});

const varela = Varela({
  weight: "400",
  variable: "--font-varela"
})

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// ----------------------------

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${DMSans.variable} ${DMSerifDisplay.variable}`}>
      <body
        className={`${geistMono.variable} ${DMSans.className} antialiased`}
      >
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
